services:
  - type: web
    name: shazam-api
    runtime: node
    repo: https://github.com/rahamanleon/Shazam-API
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: npm install
    startCommand: node api-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
